### ISSUE TITLE
Deprecate changelog/changeset DSL

### ISSUE THREAD

**Issue by kumarshantanu** [kumarshantanu/clj-liquibase#8]
The changelog/changeset DSL was developed when XML used to be the only way to write Liquibase changelogs. Now Liquibase supports YAML and SQL files (beside XML) for writing changelogs -- the complexity incurred with the Clojure DSL may be unnecessary. Moreover, the Liquibase API has changed internally between Liquibase version 3.0 and 3.1, which breaks the DSL.

This issue is to invite votes on deprecating the changelog/changeset DSL for clj-liquibase 0.6.0 release. Pinging past contributors @john-roj87 @cgore @jakemcc for opinion.

**Comment by cgore** [comment]
I haven't had the opportunity to use liquibase since leaving Outpace, so I'll bow out of this decision and trust everybody else's judgement on it.

**Comment by jakemcc** [comment]
@kumarshantanu Sorry for taking a while to respond. I as traveling a bit.

I'm not entirely sure which aspect you're thinking about deprecating. Which aspect do you consider the DSL?

**Comment by kumarshantanu** [comment]
@jakemcc By DSL I mean `defchangelog` and the changeset/change (e.g. `create-table`) data structures/API.

As an alternative to the DSL, I am planning to include https://github.com/kumarshantanu/liquibase-edn in the 0.6.0 release.

**Comment by jakemcc** [comment]
@kumarshantanu I currently make heavy use of the the various functions inside the `clj-liquidbase.change` namespace (`add-columns`, `create-table`, etc). Selfishly I'd prefer to continue writing migrations in Clojure files using those functions.

I can image that describing the migrations using edn could be workable.

If you want to deprecate functionality you should feel free to do so though. People (including potentially myself) can just stick with previous versions until they're forced to upgrade because of some missing feature.

**Comment by john-roj87** [comment]
On my projects we ended up creating a leiningen plugin wrapper around liquibase. So we are not currently using this lib anymore.
I am towards agreeing with @kumarshantanu maybe the DSL is probably overkill and it is much more harder to maintain.

**Comment by kumarshantanu** [comment]
Update: I have added support for parsing changelog files and included EDN parser to `master`.

**Comment by kumarshantanu** [comment]
Deprecated the old changelog/changeset DSL via https://github.com/kumarshantanu/clj-liquibase/commit/2ffb68d0e515134c912167344db89ec4cd20602f and released version `0.6.0` - thanks everybody for input.
